[build]
  command = "bun run build"
  publish = "dist"

[dev]
  command = "bun run dev"
  port = 4321
  targetPort = 4321

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: blob: https://*; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cloud.umami.is https://fundingchoicesmessages.google.com https://pagead2.googlesyndication.com https://unpkg.com; style-src 'self' 'unsafe-inline'; connect-src 'self' https://cloud.umami.is wss://*; frame-src 'self' https://fundingchoicesmessages.google.com;"
