name: LHCI-output-webhook
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://breadmine.neealdon3-3f0.workers.dev/
            https://bromine.pages.dev/
            https://bromine.on-to.space
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

      - name: Send Lighthouse Links to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.ACTIONS_WEBHOOK_URL }}
          RAW_LINKS_OUTPUT: ${{ steps.LHCIAction.outputs.links }}
        run: |
          # 1. Format the links into a single string with newlines for the message
          # This creates a bulleted list like: "- https://report1.html\n- https://report2.html"
          FORMATTED_CONTENT=$(echo "$RAW_LINKS_OUTPUT" | jq -r 'to_entries | map("- <\(.value)>") | join("\n")')

          # 2. Safely build the JSON payload using jq
          # This prevents syntax errors from special characters or newlines
          JSON_PAYLOAD=$(jq -n \
                            --arg username "Lighthouse Bot" \
                            --arg content "$FORMATTED_CONTENT" \
                            '{username: $username, content: $content}')

          # 3. Send the payload to Discord
          curl -X POST -H "Content-Type: application/json" \
               -d "$JSON_PAYLOAD" \
               "${DISCORD_WEBHOOK_URL}"
