name: Lighthouse CI
on: 
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://breadmine.neealdon3-3f0.workers.dev/
            https://bromine.pages.dev/
            https://bromine.on-to.space
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      - name: Webhook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{secrets.ACTIONS_WEBHOOK_URL}}
          data: '{ "links": ${{ toJson(steps.LHCIAction.outputs.links) }}, "manifest": ${{ toJson(steps.LHCIAction.outputs.manifest) }} }'
