name: LHCI-output-webhook
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://breadmine.neealdon3-3f0.workers.dev/
            https://bromine.pages.dev/
            https://bromine.on-to.space
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
        
      - name: Send Lighthouse Links to Discord via Embed
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.ACTIONS_WEBHOOK_URL }}
          RAW_LINKS_OUTPUT: ${{ steps.LHCIAction.outputs.links }}
        run: |
          # 1. Format a description showing each site and its corresponding report link
          FORMATTED_DESCRIPTION=$(echo "$RAW_LINKS_OUTPUT" | jq -r '
            [
              to_entries | . as $items | range(length) as $i |
              "\($i + 1). **[\($items[$i].key)](\($items[$i].key))**\n   ↳ [View Lighthouse Report](\($items[$i].value))"
            ] | join("\n\n")
          ')

          # 2. Get the current timestamp in ISO 8601 format
          TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%S.000Z)

          # 3. Safely build the JSON payload with the new description
          JSON_PAYLOAD=$(jq -n \
                            --arg username "Lighthouse Bot" \
                            --arg description "$FORMATTED_DESCRIPTION" \
                            --arg timestamp "$TIMESTAMP" \
                            '{
                              "username": $username,
                              "avatar_url": "https://raw.githubusercontent.com/GoogleChrome/lighthouse/main/assets/lighthouse-logo.png",
                              "embeds": [
                                {
                                  "title": "✅ Lighthouse Scan Results",
                                  "description": $description,
                                  "color": 3447003,
                                  "footer": {
                                    "text": "Report generated by Lighthouse CI"
                                  },
                                  "timestamp": $timestamp
                                }
                              ]
                            }')

          # 4. Send the embed payload to Discord
          curl -X POST -H "Content-Type: application/json" \
               -d "$JSON_PAYLOAD" \
               "${DISCORD_WEBHOOK_URL}"
