name: LHCI-output-webhook
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://breadmine.neealdon3-3f0.workers.dev/
            https://bromine.pages.dev/
            https://bromine.on-to.space
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

      # Step 3: Send all captured clickable Lighthouse links to Discord
      - name: Send All Clickable Lighthouse Links to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.ACTIONS_WEBHOOK_URL }} # Your Discord webhook URL secret
        run: |
          RAW_LINKS_OUTPUT="${{ steps.LHCIAction.outputs.links }}"
          
          FORMATTED_LINKS=$(echo "$RAW_LINKS_OUTPUT" | jq -r 'map(.) | .[]' | sed 's/$/\\n/')

          DISCORD_PAYLOAD="{
            \"username\": \"Lighthouse CI Bot\",
            \"content\": \"${FORMATTED_LINKS}\"
          }"

          curl -X POST -H "Content-Type: application/json" \
               -d "${DISCORD_PAYLOAD}" \
               "${{ env.DISCORD_WEBHOOK_URL }}"
