name: Lighthouse CI - Use Action, Send Links (No HTML)
on: 
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Audit URLs using Lighthouse Action
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://breadmine.neealdon3-3f0.workers.dev/
            https://bromine.pages.dev/
            https://bromine.on-to.space
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Send Clickable Lighthouse Links to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.ACTIONS_WEBHOOK_URL }}
          LINKS: ${{steps.LHCIAction.outputs.links}}
        run: |          
          TEMPORARY_STORAGE_URL="${{ steps.lighthouse_audit.outputs.temporaryPublicStorageUrl }}"
          MESSAGE_CONTENT="Lighthouse CI Audit Complete for ${{ github.event.repository.full_name }} (${{ github.sha }})\n\n"
          
          if [ -n "$TEMPORARY_STORAGE_URL" ]; then
            MESSAGE_CONTENT+="**Lighthouse Report Link:**\n"
            MESSAGE_CONTENT+="- ${TEMPORARY_STORAGE_URL}\n\n"
            MESSAGE_CONTENT+="*(This link is typically for the last audited URL. If you audited multiple sites, **please check the GitHub Actions workflow run logs for all individual temporary links**, under the 'Audit URLs using Lighthouse Action' step.)*\n"
          else
            MESSAGE_CONTENT+="No temporary Lighthouse report link was found from the action's output. Please check the workflow logs for details."
          fi

          MESSAGE_CONTENT+="\n*(Click on the link to view the detailed Lighthouse report in your browser.)*"

          ESCAPED_MESSAGE_CONTENT=$(echo "$MESSAGE_CONTENT" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
          curl -X POST -H "Content-Type: application/json" \
                # \"${ESCAPED_MESSAGE_CONTENT}\"
               -d "{\"content\": $LINKS, \"username\": \"Lighthouse CI Bot\"}" \
               "${{ env.DISCORD_WEBHOOK_URL }}"
