name: CI
on: 
  workflow_dispatch:
    
jobs:
  Lighthouse-CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install && bun install -g @lhci/cli@0.15.x
      - run: bun run build
      - run: lhci autorun --serverBaseUrl='https://bromine.on-to.space/'
      
